### PR TITLE
rpi2: add missing --recursive argument for git clone

### PR DESCRIPTION
**Pull request by coldnew**
Since this repo contains git submodule, add missing --recursive
argment for rpi2's tutorial.

Signed-off-by: Yen-Chin Lee <coldnew.tw@gmail.com>

### CODE REVIEW

**Comment by cirosantilli** [comment]
Hey,

This should not be necessary, because QEMU is only needed for x86 hosts, and binutils is currently only needed for SVE, which RPI does not have.

`make NATIVE=y` then just uses the PI's native compiler.

What I'd rather do instead is to skip the SVE example on PI3 v8.

**Comment by coldnew** [comment]
I think wahat you said is right, the binutils should not builded under Raspberry Pi 2.

When I draft this PR, I had following error on building `v7` on my rpi2

```
pi@c2:~/arm-assembly-cheat/v7 $ make NATIVE=y test
mkdir -p '/home/pi/arm-assembly-cheat/out/binutils-gdb/build/arm'
cd '/home/pi/arm-assembly-cheat/out/binutils-gdb/build/arm' && \
"/home/pi/arm-assembly-cheat/binutils-gdb/configure" \
  --target 'arm-elf' \
  --prefix '/home/pi/arm-assembly-cheat/out/binutils-gdb/install' \
&& \
make -j`nproc` && \
make -j`nproc` install
/bin/sh: 2: /home/pi/arm-assembly-cheat/binutils-gdb/configure: not found
Makefile:172: recipe for target '/home/pi/arm-assembly-cheat/out/binutils-gdb/install/bin/arm-elf-as' failed
make: *** [/home/pi/arm-assembly-cheat/out/binutils-gdb/install/bin/arm-elf-as] Error 127

```

and ..

```
pi@c2:~/arm-assembly-cheat/v7 $ make NATIVE=y gdb-add
gcc -ggdb3 -march=armv7-a -pedantic -std=c99 -Wall -Wextra  -marm  -c -o 'main.o' 'main.c'
cpp -o 'add.S.tmp' 'add.S'
/home/pi/arm-assembly-cheat/out/binutils-gdb/install/bin/arm-elf-as --gdwarf-2 -march=armv7-a -mfpu=neon-vfpv3 -meabi=5 -c -o 'add.o' 'add.S.tmp'
make: /home/pi/arm-assembly-cheat/out/binutils-gdb/install/bin/arm-elf-as: Command not found
Makefile:96: recipe for target 'add.o' failed
make: *** [add.o] Error 127

```

I'll figure out what's wrong :(

**Comment by cirosantilli** [comment]
@coldnew let me know if https://github.com/cirosantilli/arm-assembly-cheat/commit/bcddf29c8e00b30afe7b3643558b25f22a64405b solves the problem. Thanks for this report, let me know if you find any other bugs.

I refactored some stuff, but didn't make AS=as for NATIVE, and I don't test on Pi that often, though I do want to support it as well as possible.

Now I also noticed that some compilation flags were broken on the newer Raspbian and fixed, and that VFP is not working, so I commented out for now.

**Comment by coldnew** [comment]
Hi @cirosantilli 

I had test bcddf29 on my Raspberry Pi2, and the problem is gone.

Thanks for your works :+1:

**Pull request closed without merging**
